[build]
  command = "npm ci"  # 使用 npm ci 来严格安装依赖
  publish = "public"

  [build.environment]
  NODE_ENV = "production"



[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://builtatlightspeed.com, https://jamstackthemes.dev"

    


