[build]
  command = "npm ci"  # 使用 npm ci 或 yarn install
  publish = "public"  # 发布目录

  [build.environment]
  NODE_ENV = "production"




[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://builtatlightspeed.com, https://jamstackthemes.dev"

    


